config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'

  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/purchase',  to: 'users#purchase'

  resources :rewards, only: [:show, :index]

  resources :users, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :rewards, only: [:new, :create, :index]
  end

  resources :admin do
    resources :rewards, :controller => 'admin/rewards'
    resources :users, :controller => 'admin/users'
  end
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  has_many :user_rewards
  has_many :users, through: :user_rewards
  validates :name, presence: true, uniqueness: true
  validates :point_value, presence: true

  has_attached_file :image, styles: {thumb: '150 x 150'}
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :user_rewards
  has_many :rewards, through: :user_rewards
  validates :username, presence: true, uniqueness: true

  enum role: %w(default admin)

  def self.buy_reward(user, reward)
    error = nil
    if user.points_available.nil?
      error = "You don't have any points, you can't buy anything!!!"
    elsif reward.point_value > user.points_available
      error = "You don't have enought points for this!!!"
    else
      new_points_available = user.points_available - reward.point_value
      new_redeemed_points = user.points_redeemed + reward.point_value
      user.update_attributes!(points_available: new_points_available)
      user.update_attributes!(points_redeemed: new_redeemed_points)
      user.rewards << reward
      user.save
    end
    error
  end
end

app/models/user_reward.rb
class UserReward < ActiveRecord::Base
  belongs_to :user
  belongs_to :reward
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin
end

app/controllers/admin/rewards_controller.rb
class Admin::RewardsController < Admin::BaseController
  before_action :set_up

  def set_up
    @admin = current_user
    @reward = Reward.new
  end

  def new
  end

  def create
    @reward = Reward.new(reward_params)
    if @reward.save
      flash[:notice] = "You successfuly created a reward!"
      redirect_to admin_path(params[:admin_id])
    else
      flash.now[:error] = @user.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit
    @reward = Reward.find(params[:id])
  end

  def update
    @reward = Reward.find(params[:id])
    if @reward.update(reward_params)
      flash.notice = "Reward #{@reward.name} Updated!"
      redirect_to admin_path(@admin)
    else
      flash.now[:errors] = @reward.error.full_messages.join(" ,")
      render :edit
    end
  end

  def destroy
    @reward = Reward.find(params[:id])
    @reward.destroy
    flash.notice = "Reward Deleted"
    redirect_to admin_path(@admin)
  end

  private

  def reward_params
    params.require(:reward).permit(:name, :point_value, :description, :user_id, :image)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_up

  def set_up
    @admin = current_user
  end

  def new
    @new_user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_path(@admin)
    else
      flash.now[:error] = @user.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    flash.notice = "User #{@user.username} Updated!"
    redirect_to admin_path(@admin)
  end

  def destroy
    @user = User.find(params[:id])
    @user.rewards.delete_all
    @user.destroy
    flash.notice = "User Deleted"
    redirect_to admin_path(@admin)
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :first_name, :last_name, :points_available, :points_redeemed, :top_destination)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :require_admin

  def show
    @admin = current_user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_admin?, :current_user

  def require_admin
    render file: "/public/404" unless current_admin?
  end

  def require_current_user
    render file: "/public/404" unless current_user
  end

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController

  def index
    @user = current_user
  end

  def create
    @user = current_user
    @reward = Reward.find(params[:reward_id])
    error_message = User.buy_reward(@user, @reward)
    if error_message.nil?
      flash[:notice] = "You bought it!!!"
    else
      flash[:error] = error_message
    end
    redirect_to user_path(@user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  # def create # See -- Creating Actual Users on CM OAuth
  #   render text: request.env["omniauth.auth"].inspect
  # end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      if @user.role == "admin"
        redirect_to admin_path(@user.username)
      else
        redirect_to user_path(@user.username)
      end
    else
      flash.now[:error] = "Invalid. Try Again."
      render :new
    end
  end

  def destroy
    session.clear
    flash[:notice] = "Goodbye!"
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_current_user, only: [:show]

  def new
    @admin = User.find(params[:admin_id]) if params[:admin_id]
    @user = User.new
  end

  def create
    @admin = User.find(params[:admin_id]) if params[:admin_id]
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash.now[:error] = @user.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash.notice = "#{@user.username} Updated!"
      redirect_to user_path(@user)
    else
      flash.now[:errors] = @user.errors.full_messages.join(" ,")
      render :edit
    end
  end

  def show
    @user = current_user
  end

  def destroy
    @user = current_user
    @user.rewards.delete_all
    @user.destroy
    session.clear
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :first_name, :last_name, :points_available, :points_redeemed, :top_destination)
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/rewards/edit.html.erb
<h2>Edit Reward</h2>
<div class="container">
  <div class="row">
    <div class="col s12 m8 l12">
      <div class="card-panel blue-grey lighten-5">
        <%= form_for(@reward, url: admin_reward_path(@reward, admin_id: @admin)) do |f| %>
          <%= f.label :name %>
          <%= f.text_field :name %>
          <%= f.label :point_value, "Point Value" %>
          <%= f.text_field :point_value %>
          <%= f.label :description %>
          <%= f.text_field :description %>
          <% if @reward.image.exists? %>
            <%= image_tag(@reward.image.url, width:"150")%><br />
          <% end %>
          <%= f.label :image, "Upload an Image" %>
          <%= f.file_field :image %><br><br>
          <%= f.submit "Update Reward" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/rewards/new.html.erb
<h2>Hello, <%=@admin.first_name %>. Please Create Reward</h2>
<div class="container">
  <div class="row">
    <div class="col s12 m8 l12">
      <div class="card-panel blue-grey lighten-5">
        <%= form_for(@reward, url: admin_rewards_path(@admin)) do |f| %>
          <%= f.label :name %>
          <%= f.text_field :name %>
          <%= f.label :point_value, "Point Value" %>
          <%= f.text_field :point_value %>
          <%= f.label :description %>
          <%= f.text_field :description %>
          <%= f.label :image, "Upload an Image" %>
          <%= f.file_field :image %><br><br>
          <%= f.submit "Create Reward" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/show.html.erb
<h2>Admin Dashboard</h2>
<div class="row" id="admin-dashboard">
  <div class="col s12 m12">
     <div class="card blue-grey lighten-5">
       <div class="card-content white-text">
         <div class="col s12 m6">
           <div class="card blue-grey darken-1">
             <div class="card-content white-text">
              <h2>Rewards</h2>
              <h5><%= link_to "New Reward", new_admin_reward_path(@admin)  %></h5>
              <% Reward.all.each do |reward| %>
                  <div id = <%=reward.name.downcase %> >
                  <h4><%= reward.name %></h4>
                  <% if reward.image.exists? %>
                    <img class="z-depth-3" width="400"<%= image_tag(reward.image.url, width:"150")%></img><br>
                  <% end %>
                  <h5><%= reward.description %></h5>
                  <h5><%= link_to "Edit", edit_admin_reward_path(@admin, reward) %> | <%= link_to "Delete", admin_reward_path(@admin, reward), method: :delete %></h5><br><br>
                <% end %>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col s12 m6" id="app-detail-padding">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <table>
        <h2>Users</h2>
        <h5><%= link_to "New User", new_admin_user_path(@admin)  %></h5>
        <% User.all.each do |user| %>
          <div id = <%=user.username.downcase %> >
          <h4><%= user.username %></h4>
          <h5><%= link_to 'Edit User', edit_admin_user_path(@admin, user) %> | <%= link_to 'Delete User', admin_user_path(@admin, user), method: :delete %></h5><br><br>
          </div>
        <% end %>
      </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/edit.html.erb
<h2>Edit account</h2>
<div class="container">
  <div class="row">
    <div class="col s12 m8 l12">
      <div class="card-panel blue-grey lighten-5">
        <%= form_for(@user, url: admin_user_path(@user, admin_id: @admin)) do |f| %>
          <%= f.label :username %>
          <%= f.text_field :username %>
          <%= f.label :password %>
          <%= f.password_field :password %>
          <%= f.label :first_name %>
          <%= f.text_field :first_name %>
          <%= f.label :last_name %>
          <%= f.text_field :last_name %>
          <%= f.label :top_destination %>
          <%= f.text_field :top_destination %>
          <% if @admin %>
            <%= f.label :points_available %>
            <%= f.text_field :points_available %>
          <% end %>
          <%= f.submit "Update Account" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/new.html.erb
<h2>Create an account</h2>
<div class="container">
  <div class="row">
    <div class="col s12 m8 l12">
      <div class="card-panel blue-grey lighten-5">
        <%= form_for(@new_user, url: admin_users_path(@admin)) do |f| %>
          <%= f.label :username %>
          <%= f.text_field :username %>
          <%= f.label :password %>
          <%= f.password_field :password %>
          <%= f.label :first_name %>
          <%= f.text_field :first_name %>
          <%= f.label :last_name %>
          <%= f.text_field :last_name %>
          <%= f.label :top_destination %>
          <%= f.text_field :top_destination %>
          <%= f.label :points_available %>
          <%= f.text_field :points_available %>
          <%= f.submit "Create Account" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8">
    <title>Pointbox</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>

  <body>

    <header class="nav">
      <nav>
        <div class="nav-wrapper cyan darken-1">
          <a href="/" class="brand-logo">TravelPoints</a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <% if current_user.nil? %>
              <li><a href="/">Login</a></li>
            <% elsif current_user.role == "admin" %>
              <li><%= link_to "Dashboard", admin_path(current_user) %></li>
              <li><%= link_to "Create Reward", new_admin_reward_path(current_user) %></li>
              <li><%= link_to "Create User", new_admin_user_path(current_user) %></li>
              <li><%= link_to "Logout", logout_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Dashboard", user_path(current_user) %></li>
              <li><%= link_to "Logout", logout_path, method: :delete %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>

    <main>
      <div class="row">
        <div class="col s5 offset-s6 m7 offset-m2">
          <% flash.each do |type, msg| %>
          <div class="card-panel btn-large waves-effect waves-light orange">
            <h5><%= content_tag :div, msg, class: "flash_#{type}" %></h5>
          </div>
          <% end %>
        </div>
      </div>
      <div class='container'>
        <%= yield %>
      </div>
    </main>

    <footer class="page-footer cyan darken-1">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Company Bio</h5>
          <p class="grey-text text-lighten-4">We are a team of Turing students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">About</h5>
          <ul>
            <li><a class="white-text" href="#!">Company</a></li>
            <li><a class="white-text" href="#!">Outreach</a></li>
            <li><a class="white-text" href="#!">Careers</a></li>
            <li><a class="white-text" href="http://www.turing.io" target="_blank">Contact</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Destinations</h5>
          <ul>
            <li><a class="white-text" href="#!">Asia Pacific</a></li>
            <li><a class="white-text" href="#!">Europe</a></li>
            <li><a class="white-text" href="#!">Americas</a></li>
            <li><a class="white-text" href="#!">Middle East</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made by <a class="orange-text text-lighten-3" href="https://github.com/ShannonPaige" target="_blank">Shannon Paige</a> & <a class="orange-text text-lighten-3" href="https://github.com/acareaga" target="_blank">Aaron Careaga</a>
      </div>
    </div>
  </footer>
  </body>
</html>

app/views/rewards/index.html.erb
<h1>You are Now Purchasing Rewards:</h1>
<div class="row" id="admin-dashboard"><br><br>
  <div class="col s12 m12">
     <div class="card blue-grey lighten-5">
       <div class="card-content white-text">

         <div class="col s12 m12" id="app-detail-padding">
           <div class="card blue-grey darken-1">
             <div class="card-content white-text">

              <% Reward.all.each do |reward| %>
                <div id=<%="#{reward.name.downcase}" %>>
                  <h4><%= reward.name %> (<%= reward.point_value %> points)</h4>
                  <% if reward.image.exists? %>
                    <img class="z-depth-3" width="500"<%= image_tag(reward.image.url, width:"150")%></img><br>
                  <% end %>
                  <h5><%= reward.description %> - <%= link_to "Purchase Reward", user_rewards_path(@user, reward_id: reward.id), method: :post %></h5><br><br>
                </div>
              <% end %>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h2>Edit your account</h2>
<div class="container">
  <div class="row">
    <div class="col s12 m8 l12">
      <div class="card-panel blue-grey lighten-5">
        <%= form_for(@user) do |f| %>
          <%= f.label :username %>
          <%= f.text_field :username %>
          <%= f.label :password %>
          <%= f.password_field :password %>
          <%= f.label :first_name %>
          <%= f.text_field :first_name %>
          <%= f.label :last_name %>
          <%= f.text_field :last_name %>
          <%= f.label :top_destination %>
          <%= f.text_field :top_destination %>
          <%= f.submit "Update Account" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h2>Create an account</h2>
<div class="container">
  <div class="row">
    <div class="col s12 m8 l12">
      <div class="card-panel blue-grey lighten-5">
        <%= form_for(@user) do |f| %>
          <%= f.label :username %>
          <%= f.text_field :username %>
          <%= f.label :password %>
          <%= f.password_field :password %>
          <%= f.label :first_name %>
          <%= f.text_field :first_name %>
          <%= f.label :last_name %>
          <%= f.text_field :last_name %>
          <%= f.label :top_destination %>
          <%= f.text_field :top_destination %>
          <%= f.submit "Create Account" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row" id="admin-dashboard"><br><br>
  <div class="col s12 m12">
     <div class="card blue-grey lighten-5">
       <div class="card-content white-text">

         <div class="col s12 m12" id="app-detail-padding">
           <div class="card blue-grey darken-1">
             <div class="card-content white-text">

              <h1>Welcome <%= @user.first_name %></h1>
              <h5>Points: <%= @user.reload.points_available %></h5>
              <h5>Points Redeemed: <%= @user.reload.points_redeemed %></h5><br>
              <h5><%= link_to "Edit Account", edit_user_path(@user) %> | <%= link_to "Delete Account", user_path(@user), method: :delete %></h5><br>

              <h3>Rewards Purchased</h3>
              <h5><%= link_to "View Rewards to Purchase", user_rewards_path(@user) %></h5>
              <% @user.rewards.each do |reward| %>
                <h4><%= reward.name %><br></h4>
                <% if reward.image.exists? %>
                  <img class="z-depth-3" width="400"<%= image_tag(reward.image.url, width:"150")%></img><br>
                <% end %>
                <h5><%= reward.description %></h5>
              <% end %> <br>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>